### ISSUE TITLE
String arguments for begin_event functions should have static lifetime

### ISSUE THREAD

**Issue by pervognsen** [EmbarkStudios/superluminal-perf-rs#15]
Like a lot of low-overhead tracing libraries, Superluminal requires the string ID passed to PerformanceAPI_BeginEvent to have static lifetime: https://www.superluminal.eu/docs/documentation.html#instrumentation

Right now the superluminal-perf wrappers don't reflect this in their signatures, which could lead to undefined behavior. Proposed solution is to replace id: &str with id: &'static str in the begin_event* signatures.

**Comment by repi** [comment]
good catch! that they indeed should have, will fix!
