### ISSUE TITLE
Doesn't compile using MingW / GCC

### ISSUE THREAD

**Issue by CGMossa** [EmbarkStudios/superluminal-perf-rs#4]
Hey!

If I use `stable-gnu` then this crate doesn't compile.

**Comment by repi** [comment]
I'm not too familar with the Rust windows GNU chain, but this library does contain a pre-built MSVC library from Superluminal that is included so not sure if that can be compatible with the GNU target.

But PRs welcome!

**Comment by CGMossa** [comment]
Ahh, okay. This is very interesting. There are multiple angles here:

- Superluminal uses PDB, which are produced by Clang, but not by gcc (I think)
- One can use superluminal on binaries produced by Mingw (gcc) but there are no source tracking. 

Maybe one can conditionally link the libraries if the right target is made, so as to circumvent compile-error, while the whole using superluminal with gcc debug symbols is sorted out.

Unfortunately, I am need deep in trying to figure out how to include libs/dlls in a rust crate and
the frustration levels have peaked for me. I'll post and ask around, and definitely aspire to get back
to this.

Mingw and gcc is the only way we have to debug our binaries on windows. Furthermore, if one uses
mingw, then including 3rd party libraries is very easy. So there are clear advantages to the Mingw toolchain here. 

Thanks for getting back to me with this

**Comment by CGMossa** [comment]
Right, feel free to close this.
